### ISSUE TITLE
Support Redmine 3.3.X?

### ISSUE THREAD

**Issue by archonwang** [ayapapa/redmine_code_review#3]
it seems not support redmine 3.3.x
could anyone fixed it. 

I  tired it to make tracker: code review and found on the code review tab, there's nothing on the list? thanks

**Comment by ayapapa** [comment]
Hi,
You installed redmine_jenkins plugin together?
I found an issue that redmine_jenkins plugin removed other plugins' setting tabs.
If you installed  redmine_jenkins plugin, you can update it to **https://github.com/ayapapa/redmine_jenkins**' **'v1.x' branch**.
And then you will find the code review tab in the project setting.

**Comment by archonwang** [comment]
@ayapapa , Thanks so much. 

 I installed the redmine_jenkins plugin.  And I will  try it later.

**Comment by ayapapa** [comment]
@archonwang , I will close this issue.
If any problems, please reopen.
